import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
const __dirname = dirname(fileURLToPath(import.meta.url));
import { chromium } from '@playwright/test';
const AUTH = resolve(__dirname, '..', '.auth', 'alva.json');
const BASE = 'https://alva.ai';
const browser = await chromium.launch();
const ctx = await browser.newContext({ storageState: AUTH, viewport: { width: 1440, height: 900 } });
const page = await ctx.newPage();
await page.goto(`${BASE}/?tab=alerts`, { waitUntil: 'domcontentloaded' });
await page.waitForTimeout(6000);
const url = page.url();
const txt = await page.evaluate(() => document.body.innerText);
console.log('URL =', url);
console.log('len =', txt.length);
console.log('has Get Started =', /Get Started/i.test(txt));
console.log('has Alpha Radar =', /Alpha Radar/i.test(txt));
console.log('has Connect Portfolio =', /Connect Portfolio/i.test(txt));
console.log('--- first 1200 chars ---');
console.log(txt.slice(0, 1200).replace(/\n{2,}/g, '\n').trim());
await browser.close();
